custom_rules:
  import_spacing:
    name: "Wrong import spacing"
    regex: 'import[^\n]*\n\n(?!import)\w+'
    message: "Please leave two lines after imports"
    severity: warning
  already_true:
    regex: "== true"
    message: "Don't compare to true, just use the bool value."
  already_bool:
    regex: "== false"
    message: "Don't compare to false, just use !value."

disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - cyclomatic_complexity

opt_in_rules: # some rules are only opt-in
  - control_statement
  - empty_count
  - trailing_newline
  - colon
  - comma
  - conditional_returns_on_newline
  - trailing_closure
  - implicit_return
  - strict_fileprivate
  - force_try
  - force_unwrapping
  - custom_rules
  - sorted_imports

included: # paths to include during linting. `--path` is ignored if present.
  - iOSSDKExample

force_unwrapping:
  severity: error
 
force_try:
  severity: error

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  
line_length:
  warning: 160
  error: 200

vertical_whitespace:
  max_empty_lines: 2
  
large_tuple:
   warning: 3
   error: 4

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 45
  excluded: id
reporter: "xcode"
