#
# Copyright (c) 2021-2025. NICE Ltd. All rights reserved.
#
# Licensed under the NICE License;
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://github.com/nice-devone/nice-cxone-mobile-sample-ios/blob/main/LICENSE
#
# TO THE EXTENT PERMITTED BY APPLICABLE LAW, THE CXONE MOBILE SDK IS PROVIDED ON
# AN “AS IS” BASIS. NICE HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS
# OR IMPLIED, INCLUDING (WITHOUT LIMITATION) WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND TITLE.
#

include:
  - path: xcodegen/defaults.yml
    relativePaths: false
  - path: xcodegen/entitlements.yml
    relativePaths: false
  - path: xcodegen/infoPlist.yml
    relativePaths: false
  - path: xcodegen/packages.yml
    relativePaths: false
  - path: xcodegen/amazon.yml
    relativePaths: false
  - local.yml

options:
  createIntermediateGroups: true
  bundleIdPrefix: ${BUNDLE_PREFIX}

name: iOSSDKExample

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: ${BUNDLE_PREFIX}.sample

targetTemplates:
  Common:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    settings:
      base:
        PRODUCT_NAME: iOSSDKExample
        DISPLAY_NAME: "SDK Demo"
    sources:
      - path: iOSSDKExample/Sources
      - path: iOSSDKExample/Supporting Files
    dependencies:
      - package: CXoneChatSDK
      - package: CXoneChatUI
      - package: CXoneGuideUtility
      - package: PKCE
      - package: Swinject
      - package: SwinjectAutoregistration
      - package: Firebase
        product: FirebaseCrashlytics
    postCompileScripts:
      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftlint > /dev/null; then
            swiftlint --config .swiftlint.yml
          else
            echo "warning: SwiftLint not installed, run brew install swiftlint"
          fi
        name: Swiftlint
        basedOnDependencyAnalysis: false

      - script: |
          if [[ "$(uname -m)" == arm64 ]]; then
            export PATH="/opt/homebrew/bin:$PATH"
          fi

          if which swiftgen > /dev/null; then
            swiftgen config -c .swiftgen.yml
          else
            echo "warning: SwiftGen not installed, run brew install swiftgen"
          fi
        name: SwiftGen
        runOnlyWhenInstalling: true
        basedOnDependencyAnalysis: true
    preBuildScripts:
      - script: |
          # Get current git branch
          gitBranch=$(git rev-parse --abbrev-ref HEAD)
          
          # Prepare build number in the format "yyyyMMddHHmm"
          buildNumber=$(date +'%Y%m%d%H%M')

          # Get tag name if available
          gitTag=$(git tag --points-at HEAD | grep .)

          # Store values in temporary files for post-build script
          echo "$buildNumber" > "${DERIVED_FILE_DIR}/build_number.txt"
          echo "$gitBranch" > "${DERIVED_FILE_DIR}/git_branch.txt"

          if [ -n "$gitTag" ]; then
            echo "$gitTag" > "${DERIVED_FILE_DIR}/git_tag.txt"
          fi

          # Update the build number in the source Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${SRCROOT}/generated/iOSSDKExample_info.plist"
          # Add the git branch to the source Info.plist
          /usr/libexec/PlistBuddy -c "Add :GitBranch string $gitBranch" "${SRCROOT}/generated/iOSSDKExample_info.plist" || /usr/libexec/PlistBuddy -c "Set :GitBranch $gitBranch" "${SRCROOT}/generated/iOSSDKExample_info.plist"
          # Add the git tag to the source Info.plist if available
          if [ -n "$gitTag" ]; then
            /usr/libexec/PlistBuddy -c "Add :GitTag string $gitTag" "${SRCROOT}/generated/iOSSDKExample_info.plist" || /usr/libexec/PlistBuddy -c "Set :GitTag $gitTag" "${SRCROOT}/generated/iOSSDKExample_info.plist"
          fi
        name: Generate Source Build Number
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - script: |
          # Read values from temporary files created in pre-build
          if [ -f "${DERIVED_FILE_DIR}/build_number.txt" ]; then
            buildNumber=$(cat "${DERIVED_FILE_DIR}/build_number.txt")
          else
            # Fallback in case the file doesn't exist
            buildNumber="Unknown"
          fi
          
          if [ -f "${DERIVED_FILE_DIR}/git_branch.txt" ]; then
            gitBranch=$(cat "${DERIVED_FILE_DIR}/git_branch.txt")
          else
            # Fallback in case the file doesn't exist
            gitBranch=$(git rev-parse --abbrev-ref HEAD)
          fi

          if [ -f "${DERIVED_FILE_DIR}/git_tag.txt" ]; then
            gitTag=$(cat "${DERIVED_FILE_DIR}/git_tag.txt")
          else
            # Fallback in case the file doesn't exist
            gitTag=$(git tag --points-at HEAD | grep .)
          fi
          

          # Update the build number in the Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          
          # Add the git branch to the Info.plist
          /usr/libexec/PlistBuddy -c "Add :GitBranch string $gitBranch" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" || /usr/libexec/PlistBuddy -c "Set :GitBranch $gitBranch" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          
          # Add the git tag to the Info.plist if available
          if [ -n "$gitTag" ]; then
            /usr/libexec/PlistBuddy -c "Add :GitTag string $gitTag" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}" || /usr/libexec/PlistBuddy -c "Set :GitTag $gitTag" "${TARGET_BUILD_DIR}/${INFOPLIST_PATH}"
          fi

          # Update the build number in the dSYM Info.plist if it exists
          if [ -f "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist" ]; then
            /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildNumber" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist"
            
            # Add the git branch to the dSYM Info.plist
            /usr/libexec/PlistBuddy -c "Add :GitBranch string $gitBranch" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist" || /usr/libexec/PlistBuddy -c "Set :GitBranch $gitBranch" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist"
            
            # Add the git tag to the dSYM Info.plist if available
            if [ -n "$gitTag" ]; then
              /usr/libexec/PlistBuddy -c "Add :GitTag string $gitTag" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist" || /usr/libexec/PlistBuddy -c "Set :GitTag $gitTag" "${BUILT_PRODUCTS_DIR}/${WRAPPER_NAME}.dSYM/Contents/Info.plist"
            fi
          fi
        name: Generate Build Number
        basedOnDependencyAnalysis: false
      - script: |
          ${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${PRODUCT_NAME}
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Info.plist
          - $(TARGET_BUILD_DIR)/$(UNLOCALIZED_RESOURCES_FOLDER_PATH)/GoogleService-Info.plist
          - $(TARGET_BUILD_DIR)/$(EXECUTABLE_PATH)
        name: Crashlytics - Upload dSYM Files
        basedOnDependencyAnalysis: false

targets:
  iOSSDKExample:
    templates: [Common, Entitled, Info, Amazon]

schemes:
  iOSSDKExample:
    build:
      targets:
        iOSSDKExample: all
